import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-6 gap-4">
          <div className="col-start-1 col-end-2">
          <Sidebar/>
          </div>
          <div className="col-start-3 col-end-6">
          {children}
          </div>
        </div>
        
        </body>
    </html>
  );
}
